### PR TITLE
Improve "Add shards ameba."

### PR DESCRIPTION
**Pull request by Fulgurance**
Hi zw963, can you just update the pull request by cancelling just the behave that ameba squeeze the code. I want to keep it clear with the space I putted.

I will give you an example, I think you will get it directly. Everything is squeezed and the tabulations were changed:

**Before:**
```crystal
def softwareIsInstalled(software : ISM::SoftwareInformation) : Bool

            if File.exists?(software.installedFilePath)
                installedSoftware = ISM::SoftwareInformation.new
                installedSoftware.loadInformationFile(software.installedFilePath)

                equalScore = 0

                software.options.each do |option|

                    if installedSoftware.option(option.name) == option.active
                        equalScore += 1
                    elsif option.isPass
                        softwarePassNumber = software.getEnabledPassNumber
                        installedSoftwarePassNumber = installedSoftware.getEnabledPassNumber

                        if option.active
                            if !installedSoftware.passEnabled
                                equalScore += 1
                            else
                                if softwarePassNumber < installedSoftwarePassNumber
                                    equalScore += 1
                                else
                                    return false
                                end
                            end
                        end

                        if installedSoftware.option(option.name)
                            if !installedSoftware.passEnabled
                                return false
                            else
                                if softwarePassNumber < installedSoftwarePassNumber && software.passEnabled
                                    equalScore += 1
                                else
                                    return false
                                end
                            end

                        end

                    else
                        if software.passEnabled
                            equalScore += 1
                        elsif installedSoftware.option(option.name) && !option.active
                            equalScore += 1
                        else
                            return false
                        end
                    end

                end

                return (equalScore == software.options.size)
            else
                return false
            end
        end
```

**After:**
```crystal
def softwareIsInstalled(software : ISM::SoftwareInformation) : Bool
      if File.exists?(software.installedFilePath)
        installedSoftware = ISM::SoftwareInformation.new
        installedSoftware.loadInformationFile(software.installedFilePath)

        equalScore = 0

        software.options.each do |option|
          if installedSoftware.option(option.name) == option.active
            equalScore += 1
          elsif option.isPass
            softwarePassNumber = software.getEnabledPassNumber
            installedSoftwarePassNumber = installedSoftware.getEnabledPassNumber

            if option.active
              if !installedSoftware.passEnabled
                equalScore += 1
              else
                if softwarePassNumber < installedSoftwarePassNumber
                  equalScore += 1
                else
                  return false
                end
              end
            end

            if installedSoftware.option(option.name)
              if !installedSoftware.passEnabled
                return false
              else
                if softwarePassNumber < installedSoftwarePassNumber && software.passEnabled
                  equalScore += 1
                else
                  return false
                end
              end
            end
          else
            if software.passEnabled
              equalScore += 1
            elsif installedSoftware.option(option.name) && !option.active
              equalScore += 1
            else
              return false
            end
          end
        end

        (equalScore == software.options.size)
      else
        false
      end
    end
```

As you can see everything is compact now

### CODE REVIEW

**Comment by zw963** [comment]
You consider follow self-assign rule, e.g. CamelCase on file_name/method_name/variable_name instead almost all Ruby/Crystal programmer use under_score, and don't like the `crystal tool format` default rule, this will make contribute to ISM is hard.  because many Crystal developer(like me) use auto formatter on save feature, i don't know how to disable format for only ISM.

**Comment by Fulgurance** [comment]
I am happy to integrate some tools or idea, but not at the expense of my project.

That reduce the readability of the code.

So in that case, I can't accept that tool for my project.

And make contribute "hard", I don't think so. We talk just about code design.

**Comment by zw963** [comment]
No one can change the source code of your project unless him disable the official format completely.

**Comment by Fulgurance** [comment]
No one who don't want yes. Not no one.

**Comment by zw963** [comment]
> No one who don't want yes. Not no one.

When i before save code, the `crystal tool format` automatically format current edited file, which do above things, because this, collaborate is almost impossible.

**Comment by Fulgurance** [comment]
Okay, I will think about your arguments. Sorry I wasn't in a good mood yesterday, I was a bit harsh.

I think it's time to change the way how I do the things.

But it's just, rewrite all my project with CamelCase, it's a huge work man. Because my repositories use that syntax as well. It's not only ISM itself

**Comment by Fulgurance** [comment]
So where do you suggest we should start? Just integrate ameba, or start to rewrite everything ? T_T

**Comment by Fulgurance** [comment]
Actually the master branch is quite "stable" and the wiki is mostly up to date, I am in holidays as well, so we can work on it definitely

**Comment by Fulgurance** [comment]
If you don't mind, I would like you to be in charge of the integration of ameba in my project, even to configure it. You have experience with it, so will be better

**Comment by zw963** [comment]
sorry，i am out recent days and really busy on other things, discuss later
when i am back

Fulgurance ***@***.***> 于 2024年6月6日周四 17:34写道：

**Comment by Fulgurance** [comment]
No problem. It's good because this gave me time to stabilize a lot of things

**Comment by Fulgurance** [comment]
I finally fix the problem I had with the permission in the plasma environment ! And now users are visible ! I just need to fix the problem when I am testing the sound in systemsettings

**Comment by Fulgurance** [comment]
I am doing massive change on the repositories that week, included in the ISM code, avoid to do any test that week, or you will just have a lot of bugs.

I am doing changed I planned from long time. For the best :)

**Comment by Fulgurance** [comment]
Just look at the main presentation, you will see I added just a "few" new configurable parameters xD

**Pull request merged**
