### PR TITLE
Add shards ameba.

### PR DESCRIPTION
**Pull request by zw963**
Hi, i create a branch for introduce `shards` and add [ameba](https://github.com/crystal-ameba/ameba) as development dependencies.

as you can see, ameba fix some obviously issue in the code, if you don't want to follow one Rule, you can just disable in `.ameba.yml`, this branch is just a show case, as you can see, there are still many rule can be fix which excluded in the `.ameba.yml`.

I will create another branch for fix an individual file as example.

Hi, i create a branch for introduce `shards` and add [ameba](https://github.com/crystal-ameba/ameba) as development dependencies.

as you can see, ameba fix some obviously issue in the code, if you don't want to follow one Rule, you can just disable in `.ameba.yml`, this branch is just a show case, as you can see, there are still many rule can be fix which excluded in the `.ameba.yml`.

I will create another branch for fix an individual file as example.

BTW: don't worry, all changes to those file is quite safe.

### CODE REVIEW

**Comment by Fulgurance** [comment]
Hi zw963, thank you for your pull request. I will have look with attention to configure properly ameda for my project. But definitely I think it's a good tool yes.

I will come back to you

**Comment by Fulgurance** [comment]
Is it possible to ask ameba to track if there is maybe some optimisations to do, or detect some unused functions or variables ?

**Comment by Fulgurance** [comment]
The only thing is, I am not sure I am 100% fan to remove the begin and return, I feel we loose readability in the code

**Comment by zw963** [comment]
> Is it possible to ask ameba to track if there is maybe some optimisations to do, or detect some unused functions or variables ?

Yes, it's did, there are many rules which i disable it in the project_root/.ameba.yml,  you can check it.

sure, only limited features offer by ameba.

**Comment by zw963** [comment]
> The only thing is, I am not sure I am 100% fan to remove the begin and return, I feel we loose readability in the code

No, redundant return is absolutely useless. the last line always return when you use Ruby/Crystal, almost every Rubyist know it, i you add return, it only means you are return early. ameba can check this safely.

the redundant begin is same.

**Comment by Fulgurance** [comment]
Oh okay I didn't know that. Thank you. I learnt something new !

How can I solve the conflict happened with your pull request and my last commit ?

It's just I never worked before with other developpers  via git. I need to learn

**Comment by zw963** [comment]
> How can I solve the conflict happened with your pull request and my last commit ?

Done, please check.

Often, this is the responsibility of the person who created the PR. You just merge your code into master as usual,  I will pull you latest changes to my local, resolve the conflict,  and then push `--force` new resolved code onto my branch.

BTW: you can try remove the excludes like [this](https://github.com/zw963/ISM/blob/add_shards/.ameba.yml#L51-L54) in the `.ameba.yml`, try run bin/ameba again, then, let ameba tell you where is the unused arguments.

**Comment by Fulgurance** [comment]
So okay I accept your pull request. I think that tool will bring stability for my project. Thank you for your help zw963

**Comment by Fulgurance** [comment]
So okay I accept your pull request. I think that tool will bring stability for my project. 

**Thank you for your help zw963**

**Comment by zw963** [comment]
Okay, this is only the first step, then,  you can try fix all the rule which exists `excepts: ???` key in the `.ameba.yml`, there are several disabled rule you can just leave there because related to CamelCase of file name/method name/variable  name

After then, there are still many improvement can be apply after take a look.
Although,  not as simple as just run ameba can solve.

Here are just a examples:

Don't use `+` to concat strings to build a bigger string, instead always use "...#{foo}...#{bar}..." to avoid allocating strings on the heap, even, the better way is to use ``str = String.build {|io| io << "..." }`` to reduce more.

**Comment by Fulgurance** [comment]
Can I have an example for that one please ?

`str = String.build {|io| io << "..." } `

Other things as well ?

I would like to ask you if you can help me to improve my implementation with json file as well. I think I am not doing well with that part. Probably need a lot of improvement

**Comment by zw963** [comment]
> Can I have an example for that one please ?


https://crystal-lang.org/reference/1.12/guides/performance.html

>  improve my implementation with json file as well

Okay, i will, but sorry for busy on recent days

**Comment by Fulgurance** [comment]
No problem.

I think I would like to slightly change the pull request we did. It's just I would like Ameba don't squeeze my code x)

There is no space now. But apart of that, really good tool. There is a way I can amend the commit and asked you just to correct that please ?

**Comment by zw963** [comment]
> I think I would like to slightly change the pull request we did.

Don't really understand what you want, if you want amend all my commit into only one commit, i guess there is a option for that when you confirm the PR.

> There is no space now.

Could you please give a example?

**Comment by Fulgurance** [comment]
I just sent to you a request, you will see

**Comment by Fulgurance** [comment]
I will give you an example, I think you will get it directly. Everything is squeezed and the tabulations were changed:

**Before:**
```crystal
def softwareIsInstalled(software : ISM::SoftwareInformation) : Bool

            if File.exists?(software.installedFilePath)
                installedSoftware = ISM::SoftwareInformation.new
                installedSoftware.loadInformationFile(software.installedFilePath)

                equalScore = 0

                software.options.each do |option|

                    if installedSoftware.option(option.name) == option.active
                        equalScore += 1
                    elsif option.isPass
                        softwarePassNumber = software.getEnabledPassNumber
                        installedSoftwarePassNumber = installedSoftware.getEnabledPassNumber

                        if option.active
                            if !installedSoftware.passEnabled
                                equalScore += 1
                            else
                                if softwarePassNumber < installedSoftwarePassNumber
                                    equalScore += 1
                                else
                                    return false
                                end
                            end
                        end

                        if installedSoftware.option(option.name)
                            if !installedSoftware.passEnabled
                                return false
                            else
                                if softwarePassNumber < installedSoftwarePassNumber && software.passEnabled
                                    equalScore += 1
                                else
                                    return false
                                end
                            end

                        end

                    else
                        if software.passEnabled
                            equalScore += 1
                        elsif installedSoftware.option(option.name) && !option.active
                            equalScore += 1
                        else
                            return false
                        end
                    end

                end

                return (equalScore == software.options.size)
            else
                return false
            end
        end
```

**After:**
```crystal
def softwareIsInstalled(software : ISM::SoftwareInformation) : Bool
      if File.exists?(software.installedFilePath)
        installedSoftware = ISM::SoftwareInformation.new
        installedSoftware.loadInformationFile(software.installedFilePath)

        equalScore = 0

        software.options.each do |option|
          if installedSoftware.option(option.name) == option.active
            equalScore += 1
          elsif option.isPass
            softwarePassNumber = software.getEnabledPassNumber
            installedSoftwarePassNumber = installedSoftware.getEnabledPassNumber

            if option.active
              if !installedSoftware.passEnabled
                equalScore += 1
              else
                if softwarePassNumber < installedSoftwarePassNumber
                  equalScore += 1
                else
                  return false
                end
              end
            end

            if installedSoftware.option(option.name)
              if !installedSoftware.passEnabled
                return false
              else
                if softwarePassNumber < installedSoftwarePassNumber && software.passEnabled
                  equalScore += 1
                else
                  return false
                end
              end
            end
          else
            if software.passEnabled
              equalScore += 1
            elsif installedSoftware.option(option.name) && !option.active
              equalScore += 1
            else
              return false
            end
          end
        end

        (equalScore == software.options.size)
      else
        false
      end
    end
```

As you can see everything is compact now

**Comment by Fulgurance** [comment]
So I will cancel the previous pull request, if you can just correct that please. Thank you :)

**Comment by zw963** [comment]
> if you can just correct that please. Thank you :)

It format by `crystal tool format`,  it is not configuable.

https://forum.crystal-lang.org/t/ism-ingenius-system-manager-linux/5168/22?u=zw963

squeeze the unncessary blank line and change tabulations into space all consider as a good code style( for Ruby) for a long time.

**Pull request merged**
